apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dear-comrade-cloud-config
  name: dear-comrade-cloud-config
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: dear-comrade-cloud-config
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dear-comrade-cloud-config
    spec:
      containers:
      - image: dasari508201/dear-comrade-cloud-config:0.0.8
        imagePullPolicy: IfNotPresent
        name: dear-comrade-cloud-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: dear-comrade-cloud-config
  name: dear-comrade-cloud-config
  namespace: default
spec:
  ports:
  - nodePort: 30542
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: dear-comrade-cloud-config
  sessionAffinity: None
  type: LoadBalancer
